import re
import time
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

def analyze_project(data):
    # Retrieve form fields
    project_name = data.get("project_name", "").strip()
    description = data.get("description", "").strip()
    tech_stack = data.get("tech_stack", "").strip()
    deployment_target = data.get("deployment_target", "").strip()
    main_features = data.get("main_features", "").strip()
    auth_details = data.get("auth_details", "").strip()
    database_storage = data.get("database_storage", "").strip()
    external_apis = data.get("external_apis", "").strip()
    known_risks = data.get("known_risks", "").strip()

    # Heuristic scoring and analysis parameters
    score = 100
    deductions = []
    
    # 1. Requirements Clarity
    word_count = len(description.split()) + len(main_features.split())
    if word_count > 60:
        clarity_status = "High"
        clarity_desc = "The project description and feature list are highly detailed, providing a solid foundation for code generation and review."
    elif word_count > 25:
        clarity_status = "Medium"
        clarity_desc = "The project scope is moderately defined. Some features might need more specification to avoid scope creep or vibe-coding errors."
        score -= 10
        deductions.append("Moderate requirement details.")
    else:
        clarity_status = "Low"
        clarity_desc = "The project description and features are brief. Highly likely to result in misalignment between the AI-generated code and intended functionality."
        score -= 25
        deductions.append("Vague or short project description and feature details.")

    # 2. Missing Requirements Analysis
    missing_reqs = []
    if not auth_details or any(w in auth_details.lower() for w in ["none", "no auth", "n/a", "no", "not yet"]):
        missing_reqs.append("Formal authentication and authorization mechanism (currently set to none or unspecified).")
    if not database_storage or any(w in database_storage.lower() for w in ["none", "no db", "n/a", "no"]):
        # Maybe it's a static site, but if there's features it might need state persistence
        if len(main_features) > 20:
            missing_reqs.append("Persistent storage plan. If data needs to persist between restarts, an external database is required.")
    
    # Check for environmental variables configuration
    if "env" not in (tech_stack + description + auth_details).lower():
        missing_reqs.append("Environment variables configuration (.env file / secret manager setup) to isolate credentials.")

    # Check for CI/CD or build pipeline
    if not any(w in (deployment_target + description).lower() for w in ["github actions", "gitlab ci", "pipeline", "ci/cd", "jenkins"]):
        missing_reqs.append("Automated CI/CD deployment pipeline for reliable integration and delivery.")

    # 3. Security & Privacy Risks
    security_risks = []
    if not auth_details or any(w in auth_details.lower() for w in ["none", "no auth", "n/a", "no"]):
        security_risks.append("Data Exposure: Without authentication, all application routes and endpoints are accessible to anyone.")
        score -= 20
    else:
        security_risks.append("Session Hijacking / CSRF: Ensure that cookies or tokens (JWT) have Secure, HttpOnly, and SameSite flags configured.")

    if database_storage and not any(w in database_storage.lower() for w in ["none", "no db", "n/a"]):
        security_risks.append("SQL Injection or NoSQL Injection: Raw queries might be generated by the LLM. Use ORMs or parameterized queries.")
        if "sql" in database_storage.lower() or "postgres" in database_storage.lower() or "mysql" in database_storage.lower():
            security_risks.append("Database Connection Pooling: Vibe-coded connections might leak under load, leading to a Denial of Service.")
    
    if external_apis and not any(w in external_apis.lower() for w in ["none", "n/a", "no"]):
        security_risks.append("Credential Leakage: API keys or tokens might be hardcoded in the codebase instead of referenced from secrets.")
        security_risks.append("Man-in-the-Middle (MitM): Outgoing API requests must verify SSL certificates (e.g., avoid setting verify=False in Python requests).")

    if known_risks:
        security_risks.append(f"Addressed Risk: User flagged concern: '{known_risks}' - verify mitigations are in place.")
        score -= 5

    # 4. Edge Cases
    edge_cases = [
        "Network Latency/Timeout: The application might hang if external APIs or databases respond slowly or time out.",
        "Payload Size Limits: Large user inputs, uploads, or API response sizes could cause server crashes or memory exhaustion."
    ]
    if database_storage and not any(w in database_storage.lower() for w in ["none", "no db", "n/a"]):
        edge_cases.append("Concurrent Database Updates: Multiple users writing to the same record concurrently could cause race conditions.")
    if auth_details and not any(w in auth_details.lower() for w in ["none", "no auth", "n/a"]):
        edge_cases.append("Token Expiration/Renewal: User sessions expiring mid-operation, leading to unhandled 401/403 responses.")

    # 5. Testing Recommendations
    testing_recs = [
        "Unit Testing: Write tests for core algorithms, utility functions, and route handlers.",
        "Integration Testing: Mock external APIs to ensure your codebase handles failure states (500, 429, timeout) correctly."
    ]
    if auth_details and not any(w in auth_details.lower() for w in ["none", "no auth"]):
        testing_recs.append("Authentication Flows: Verify sign-up, sign-in, token refresh, and sign-out edge cases.")
    if database_storage and not any(w in database_storage.lower() for w in ["none", "no db"]):
        testing_recs.append("Database Migration: Test schema migration scripts on a staging database before running in production.")
    
    # 6. Deployment Readiness & Checklist
    checklist = []
    # Tech Stack specific checks
    ts_lower = tech_stack.lower()
    dt_lower = deployment_target.lower()
    
    if "python" in ts_lower or "flask" in ts_lower or "django" in ts_lower:
        checklist.append(("Debug Mode Disabled", True, "Ensure Flask debug mode is set to False (FLASK_DEBUG=0)."))
        checklist.append(("WSGI/ASGI Production Server", True, "Do not use the Flask built-in development server. Use Gunicorn or uWSGI."))
    elif "node" in ts_lower or "express" in ts_lower or "react" in ts_lower or "next" in ts_lower:
        checklist.append(("Production Node Environment", True, "Set NODE_ENV=production to enable speed optimizations."))
    else:
        checklist.append(("Production Compilation", True, "Verify build artifacts are optimized and minified."))

    # Target specific checks
    if "cloud run" in dt_lower or "gcp" in dt_lower or "google cloud" in dt_lower:
        checklist.append(("Containerized Configuration", True, "Dockerfile optimized for production (multi-stage build, non-root user)."))
        checklist.append(("Memory & CPU Limits", True, "Set concurrency, CPU limits, and minimum instances to manage scaling latency (cold starts)."))
        checklist.append(("GCP Secret Manager", True, "Avoid environment variables for production database passwords; inject using Secret Manager."))
    elif "aws" in dt_lower or "lambda" in dt_lower or "ecs" in dt_lower:
        checklist.append(("IAM Least Privilege Policies", True, "Check execution roles to ensure the service only has access to required AWS resources."))
        checklist.append(("AWS Secrets Manager / Parameter Store", True, "Use secure storage for system credentials instead of plaintext env parameters."))
    elif "vercel" in dt_lower or "netlify" in dt_lower:
        checklist.append(("Serverless Timeout Limits", True, "Ensure backend API actions execute within the platform time limits (typically 10-60 seconds)."))
    else:
        checklist.append(("Production Environment Configuration", True, "Set environment-specific configuration values and double-check credentials."))

    checklist.append(("HTTPS / SSL Setup", True, "Verify SSL/TLS is enforced across all communication channels."))
    checklist.append(("CORS Configurations", True, "Restrict allowed origins to trusted domains, avoiding wildcard Access-Control-Allow-Origin headers."))

    # 7. Monitoring & Logging Suggestions
    monitoring_suggestions = [
        "Structured JSON Logging: Standardize logs as JSON to make querying easier (e.g., using python-json-logger).",
        "Error Tracker Integration: Configure Sentry, Rollbar, or GlitchTip to receive real-time alerts for unhandled exceptions.",
        "Health Check Endpoint: Create a dedicated '/healthz' or '/health' endpoint for container orchestration liveness/readiness probes."
    ]
    if "cloud run" in dt_lower or "gcp" in dt_lower or "google cloud" in dt_lower:
        monitoring_suggestions.append("GCP Cloud Logging & Cloud Monitoring: Set up alerts on HTTP 5xx rate spikes and high latency.")
    elif "aws" in dt_lower or "lambda" in dt_lower:
        monitoring_suggestions.append("AWS CloudWatch Alarms: Create alarms for Lambda duration limits, invocation errors, and throttles.")

    # Deduct score for missing items
    if len(missing_reqs) > 0:
        score -= (len(missing_reqs) * 8)
    
    score = max(0, min(100, score))

    # 8. Final Recommendation
    if score >= 85:
        recommendation_status = "Ready to Deploy"
        recommendation_explanation = "The application follows best practices, has minimal structural risks, and features clear specifications. You are ready to push to production once the checklist is complete."
    elif score >= 50:
        recommendation_status = "Needs Minor Fixes"
        recommendation_explanation = "The project is well-scoped but contains outstanding issues (e.g., missing specific environment isolation, basic security adjustments, or incomplete testing scripts). Resolve these items before deploying."
    else:
        recommendation_status = "Not Ready"
        recommendation_explanation = "Critical gaps detected: missing authentication, poor requirement clarity, or potential security vulnerabilities. Deploying in this state carries high risk of downtime, data leakage, or failure."

    # Return structured review dictionary
    return {
        "score": score,
        "clarity": {
            "status": clarity_status,
            "description": clarity_desc
        },
        "missing_requirements": missing_reqs if missing_reqs else ["None identified. Requirements look complete for this phase."],
        "security_risks": security_risks if security_risks else ["No major security vulnerabilities detected in the spec."],
        "edge_cases": edge_cases,
        "testing_recommendations": testing_recs,
        "deployment_readiness": {
            "score": score,
            "checklist": [{"title": c[0], "status": "Pending", "description": c[2]} for c in checklist]
        },
        "monitoring_logging": monitoring_suggestions,
        "final_recommendation": {
            "status": recommendation_status,
            "explanation": recommendation_explanation
        }
    }

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/review", methods=["POST"])
def review_project():
    # Simulate a brief delay to show loading animation and feel realistic
    time.sleep(1.5)
    
    data = request.json or {}
    if not data.get("project_name"):
        return jsonify({"error": "Project Name is required"}), 400
        
    review = analyze_project(data)
    return jsonify(review)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
